# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-24 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('org', '培训机构'), ('colleges', '高校'), ('personal', '个人')], default='org', max_length=20, verbose_name='机构类别'),
        ),
    ]
