# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-02 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='desc',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='讲师描述'),
        ),
    ]
