# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-06 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('cj', '初级'), ('zj', '中级'), ('gj', '高级'), ('dj', '顶级')], max_length=2, verbose_name='等级'),
        ),
    ]
