# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='learn_times',
            field=models.IntegerField(default=0, help_text='存储单位是分钟', verbose_name='学习时长'),
        ),
    ]
