# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-20 16:40
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_is_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCourse',
            fields=[
            ],
            options={
                'verbose_name_plural': '课程轮播图',
                'verbose_name': '课程轮播图',
                'proxy': True,
            },
            bases=('course.course',),
        ),
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('cj', '初级'), ('zj', '中级'), ('gj', '高级'), ('dj', '顶级')], default='cj', max_length=2, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='课程详情'),
        ),
    ]
