# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180207_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userask',
            old_name='moblie',
            new_name='mobile',
        ),
    ]
