# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20180226_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavortie',
            name='fav_type',
            field=models.IntegerField(choices=[(1, '课程'), (2, '讲师'), (3, '机构')], default=1, verbose_name='收藏类型'),
        ),
    ]
